version: '3.8'

services:
  db:
    image: postgres:15
    container_name: flexpark_db
    restart: always
    environment:
      POSTGRES_USER: flexuser
      POSTGRES_PASSWORD: flexpass
      POSTGRES_DB: flexpark_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
